### ISSUE TITLE
Update regex-automata dependency

### ISSUE THREAD

**Issue by link2xt** [hawkw/matchers#3]
This crate still dependends on regex-automata 0.1, but the latest version of regex-automata is 0.3.3.

**Comment by smalis-msft** [comment]
Yes please.

**Comment by matthiasbeyer** [comment]
Bumping this. I just found this by analyzing a project with cargo-bloat and the regex crates make up a large portion, especially regex-automata (which is included twice because this crate still depends on the old version).

**Comment by smalis-msft** [comment]
Just hit this too. Also noticed the last commit here was 2 years ago, is this crate still maintained?

**Comment by link2xt** [comment]
cc @hawkw

**Comment by hawkw** [comment]
This crate did not update to `regex-automata` v0.2 because that release's documentation stated that it was not suitable for use in most cases and existing dependencies should remain on v0.1. 

I'll investigate updating to v0.4.

**Comment by smalis-msft** [comment]
Do you mean v0.3? v0.4 isn't out yet. Or do you mean you're not planning to update until a future v0.4 is released? v0.3 doesn't contain the warning documentation that v0.2 did.

**Comment by hawkw** [comment]
> Do you mean v0.3? v0.4 isn't out yet. Or do you mean you're not planning to update until a future v0.4 is released? v0.3 doesn't contain the warning documentation that v0.2 did.

My bad, that was a typo.
